### ISSUE TITLE
how to find Port for index page of app?

### ISSUE THREAD

**Issue by Redshado0w** [sadra/EasyMTPorto#2]
hi all dears 
how to find this port for config json?

**Comment by sadra** [comment]
The `config.json` file is in the root directory.
|
| - bin \ ..
| - public \ ..
| - routes \ ..
| - views \ ..
| - .gitignore
| - EasyMTPorto.iml
| - LICENSE
| - README.md
| - `config.json`
| - emtproto.js
| - package.json
